# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Lintly-Flake8
        # You may pin to the exact commit or the version.
        # uses: grantmcconnaughey/lintly-flake8-github-action@ffa7dc0468c57e851592b84d509de1d7c6b88acf
        uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        with:
          # The GitHub API token to use for creating PR reviews
          token: ${{ secrets.GITHUB_TOKEN }}
          # Fail if *any* violations are detected or only *new* ones (valid values are "new" or "any")
          failIf: any
          # Args to pass to the flake8 executable
          args: "--max-line-length=100 ."